config/routes.rb
# -*- encoding : utf-8 -*-
Rails.application.routes.draw do
  devise_for :users
  root 'articles#welcome'

  resources :articles do
    collection do
      get :welcome
      get :markdown
    end
  end
  resources :classifications

  namespace :interface do
    resources :articles, :only => [] do
      collection do
        get :all_articles
        get :article_details
      end
    end
  end

  mount Ckeditor::Engine => '/ckeditor'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :classification
  is_impressionable

  def previous_post
    Article.where("id < ?", self.id).last
  end

  def next_post
    Article.where("id > ?", self.id).first
  end

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/classification.rb
class Classification < ActiveRecord::Base
  has_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
# -*- encoding : utf-8 -*-
class ArticlesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show,:welcome]
  impressionist :actions=>[:show,:index,:welcome]

  def new
    @article = Article.new
    @classifications = Classification.all
  end

  def index
    @classification = Classification.find_by_name(params[:classification_name])
    @articles = @classification.articles.all.order('created_at DESC')
    @all_articles_impressionist_counts_ip = 0
    @all_articles_impressionist_counts_num = 0
    @articles.each do |article|
        @all_articles_impressionist_counts_ip += article.impressionist_count(:filter=>:ip_address).to_i
        @all_articles_impressionist_counts_num += article.impressionist_count().to_i
    end
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to @article
  end

  def show
    @article = Article.find(params[:id])
    @article.impressionist_count(:filter=>:ip_address)
  end

  def edit
    @article = Article.find(params[:id])
    @classifications = Classification.all
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      redirect_to :back
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def welcome
    render 'welcome'
  end

  def markdown
    render 'markdown'
  end

  private
  def article_params
    params.require(:article).permit(:title, :text, :classification_id)
  end
end

app/controllers/classifications_controller.rb
# -*- encoding : utf-8 -*-
class ClassificationsController < ApplicationController
  before_action :authenticate_user!
  def new
    @classification = Classification.new
  end

  def index
    @classifications = Classification.all
  end

  def create
    @classification = Classification.new(classification_params)
    @classification.update(display: params[:display])
    @classification.save

    redirect_to @classification
  end

  def show
    @classification = Classification.find(params[:id])
  end

  def edit
    @classification = Classification.find(params[:id])
  end

  def update
    @classification = Classification.find(params[:id])
    @classification.update(display: params[:display])
    if @classification.update(classification_params)
      redirect_to @classification
    else
      render 'edit'
    end
  end

  def destroy
    @classification = Classification.find(params[:id])
    @classification.destroy
    redirect_to classifications_path
  end

  private
  def classification_params
    params.require(:classification).permit(:name, :display )
  end
end

app/controllers/interface/articles_controller.rb
# -*- encoding : utf-8 -*-
class Interface::ArticlesController < ActionController::Base
  def all_articles
    titles = Article.all.order(created_at: :desc).map do |article|
      {
        :id => article.id,
        :title => article.title,
        :classification => article.classification.name || '',
        :created_at => article.created_at.strftime("%m-%d %Y")
      }
    end
    render :json =>{
      result: titles
    }
  end

  def article_details
    article = Article.find params[:article_id]
    render :json => {
      result: article
    }
  end

end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <table class='table table-hover table-striped'>
    <tr>
      <td><%= f.text_field :title ,class: 'form-control', :placeholder=>'标题' %></td>
    </tr>
    <tr>
      <td>
        <%= f.select :classification_id, options_for_select( @classifications.map{ |classification| [ classification.name , classification.id ] }) %>
      </td>
    </tr>
    <tr>
      <td><%= f.cktext_area :text%></td>
    </tr>
    <tr>
      <td> <%= f.submit '确定', class: 'btn btn-primary'%><%= link_to '返回', articles_path , class: 'btn btn-default'%> </td>
    </tr>
  </table>
<% end %>

app/views/articles/_page_control.html.erb
<div class="pagination" style="width: 100%;">
  <ul>
    <li class="previous"><span class="fui-arrow-left"></span><%= link_to(@article.previous_post.title, @article.previous_post) if @article.previous_post %> </li>
  </ul>
  <ul style="float:right;">
    <li class="next"><%= link_to(@article.next_post.title, @article.next_post,) if @article.next_post %><span class="fui-arrow-right"></span></li>
  </ul>
</div>

app/views/articles/edit.html.erb
<h3>编辑文章</h3>
<%= render 'form' %>

app/views/articles/index.html.erb
<p class="palette-paragraph" style="float: right;margin-top: 10px;">
  <strong><%= "共#{@all_articles_impressionist_counts_ip}个ip访问过#{@all_articles_impressionist_counts_num}次" %></strong>
  <strong>求知要踏踏实实,做人要老老实实</strong>
</p>
<div style="margin-top:50px;">
  <% @articles.each do |article| %>
    <h5>
      <span class="fui-document" style="margin-right: 21px;"></span><%= link_to truncate(article.title),article_path(article) %>
      <span class="palette-paragraph" style="float: right;margin-left: 10px;"><strong><%= article.created_at.strftime("%Y-%m-%e") %></strong></span>
    </h5>
  <% end %>
</div>

app/views/articles/markdown.html.erb
<table>
  <tr>
    <td>
      <textarea id="text-input" oninput="this.editor.update()" rows="6" cols="60"></textarea>
    </td>
    <td>
      <div id="preview"> </div>
    </td>
  </tr>
</table>
<script src="/assets/markdown.js"></script>
<script>
  function Editor(input, preview) {
    this.update = function () {
      preview.innerHTML = markdown.toHTML(input.value);
    };
    input.editor = this;
    this.update();
  }
  var $ = function (id) { return document.getElementById(id); };
  new Editor($("text-input"), $("preview"));
</script>

app/views/articles/new.html.erb
<h3>新建文章</h3>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 style=" margin-bottom: 100px; "><%= @article.title %></h2>
<blockquote><%=raw @article.text %></blockquote>
<%= render 'page_control' %>

app/views/articles/welcome.html.erb
<h3>黄敏的站点</h3>
<p>欢迎来到我的个人网站(huangmin.me)。我是黄敏,目前在使用Titanium移动开发和Rails Web开发的工程师。 目前正在学习和使用liunx,Git,Nginx,Vim一些开发工具进行开发。</p>
<p>喜欢与厉害的人交流学习,从他们身上看到我所不具备的优点。</p>
<p>2015年毕业,目前开发过几个APP项目,有一定的项目经验。目前跟着<a href='http://siwei.me'>思维</a>学习技术和做项目。</p>

<p>欢迎给我写信: huangmin0822@163.com<p>

app/views/blogs/index.html.erb
<div class="hero-unit">
  <blockquote>
    <p>盖士人读书</p>
    <p>第一要有志，第二要有识，第三要有恒</p>
    <p>有志则断不甘为下流</p>
    <p>有识则知学问无尽,不敢以一得自足</p>
    <p>有恒则断无不成之事</p>
    <small>曾国藩<cite title="Source Title"></cite></small>
  </blockquote>
</div>
<table class="table table-striped table-hover">
  <% @blogs.each do |blog| %>
    <tr>
    <td>
      <i class="icon-leaf"></i>
      <%= link_to "#{blog.created_at} #{blog.title}",blog_path(blog) %>
    </td>
  </tr>
<% end %>
</table>

app/views/blogs/show.html.erb
<table class="table table-striped">
  <tr><td><h1> <%= @blog.title %></h1></td></tr>
  <tr><td><p><%=raw @blog.text %></p></td></tr>
</table>
<ul class="pager">
  <li class="previous"> <a href="#">&larr; Older</a> </li>
  <li><%= link_to 'Back', blogs_path %></li>
  <li class="next"><a href="#" left='0'>Newer &rarr;</a></li>
</ul>

app/views/classifications/_form.html.erb
<table class='table table-hover table-striped'>
  <%= form_for @classification do |f| %>
    <tr>
      <td>
        <%= f.text_field :name, class: 'form-control',:placeholder=>"分类名字"%>
      </td>
    </tr>
    <tr>
      <td>
        <%= radio_button_tag :display, true, :checked => @classification.display %>
        <label class="radio-inline" for='display_true'>是</label>
        <%= radio_button_tag :display, false, false, :style => 'margin-left: 50px' %>
        <label class="radio-inline" for='display_false'>否</label>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.submit '确定', class: 'btn btn-primary'%>
        <%= link_to '返回', articles_path , class: 'btn btn-default' ,style: " margin-left: 100px; "%>
      </td>
    </tr>
  <% end %>
</table>

app/views/classifications/edit.html.erb
<h1>编辑分类</h1>
<%= link_to 'Back', classifications_path %>
<%= render 'form' %>
<%= link_to 'Back', classifications_path %>

app/views/classifications/index.html.erb
<%= link_to 'New classification', new_classification_path %>
<table class="table table-striped table-hover">
  <tr>
    <th>标题</th>
    <th colspan="3"></th>
  </tr>
   
  <% @classifications.each do |classification| %>
    <tr>
      <td><%= link_to "#{classification.name}", edit_classification_path(classification) %></td>
      <td><%= link_to 'Show', classification_path(classification) %></td>
      <td><%= link_to 'Destroy', classification_path(classification), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/classifications/new.html.erb
<h3>新建分类</h3>
<%= render 'form' %>

app/views/classifications/show.html.erb
<%= link_to 'Back', classifications_path %>
| <%= link_to 'Edit', edit_classification_path(@classification) %>
<table class="table table-striped">
  <tr><td><h1> <%= @classification.name %></h1></td></tr>
  <tr><td><p><%=raw @classification.display %></p></td></tr>
</table>
<%= link_to 'Back', classifications_path %>
| <%= link_to 'Edit', edit_classification_path(@classification) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>欢迎来到黄敏的个人站点:huangmin.me</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
    <meta name="baidu-site-verification" content="q6D8HWWSQQ" />
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="row clearfix">
        <div class="col-md-12 column">
          <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="/">Huangmin</a>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <% Classification.where("display = ?","#{true}").each do |classification| %>
                <li><a href="/articles?classification_name=<%= classification.name%>"><%= classification.name %></a></li>
              <% end %>
              <li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li>
                <a href="/classifications">分类管理</a>
                </li>
                </li>
                <li><%= link_to "欢迎你：#{current_user.try :email}" %></li>
                <li> <%= link_to '退出', destroy_user_session_path, :method => :delete  %> </li>
              <% else %>
                <li>
                <%= link_to '登陆' , '/users/sign_in', :method => :get%>
                </li>
              <% end %>
            </ul>
          </ul>
        </div>

        </nav>
      </div>
    </div>
  </div>

  <div class="container" style=" margin-top: 50px; ">
    <%= yield %>
  </div>


  <script>
    $(".navbar-fixed-top").headroom();
  </script>

  <!--
  <script>
    $(document).ready(function(){
      $('li').click(function(e){
        $(this).addClass('animated bounceOutDown').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function(){
          $(this).removeClass();
        });
      });
    });
  </script>
  -->
</body>
</html>